### ISSUE TITLE
dynamic ticket field is not accessible in signature

### ISSUE THREAD

**Issue by chroto** [drukwerkdeal/zendesk_addsignatureforbrand#1]
Greetings!

We tried installing this plugin on our account but could not get it to work using the example in the README.  We opened up an issue with Zendesk Support and this was their reply:

> Unfortunately it's not possible to reference custom ticket fields in an agent signature. While you can use placeholders, the signature does not have access to the 'ticket' placeholder class. You can see this mentioned in the first paragraph of the signature documentation, which I have linked here for your convenience:
> https://support.zendesk.com/hc/en-us/articles/203691076-Adding-an-agent-signature-to-ticket-email-notifications
> 
> The workaround using triggers I mentioned will be the best way of accomplishing your desired result, unfortunately we can not support third-party code snippets and solutions.

Are we using the plugin incorrectly or has there been a recent breaking change made by Zendesk?

**Comment by printdeal** [comment]
Hi Chroto!

What you have to do, is create a dynamic content called "signature". Then, in the settings of this plugin, you set the dynamic content placeholder to {signature}. From now on, before your ticket is submitted, this placeholder is added to the end of content. And, while this happens before submitting, all placeholders are parsed, even the ones Zendesk says you can't access in the signature. That's because we don't use the real agent signature, but instead dynamic content...

Regards,

Sander Scheer
Drukwerkdeal
